# Pentagon numbers
# Problem 44
# Published on Friday, 23rd May 2003, 06:00 pm; Solved by 24416
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

require 'set'


pen = []

 (1..3000).each do |x| 
  pen << x*(3*x-1)/2
 end
 
 pen = pen.to_set
 puts pen.to_a.combination(2).select{|a,b|
   pen.include?(a+b) && pen.include?((a-b).abs)
  }.map{|a,b| (a-b).abs }.min
  
 
 
 
# set = []
# pen.each do |x|
      # pen.each do |y|
	  # set <<  (x - y) if  pen.include?(x+y) #and pen.include?(x-y) 
	# end
# end
 
# e = pen.to_enum