# Triangular, pentagonal, and hexagonal
# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


tri = []
pen = []
hex = []

(1..100000).each do |x| 
  tri << x*(x+1)/2
 end
 
 (1..100000).each do |x| 
  pen << x*(3*x-1)/2
 end
 
 (1..100000).each do |x| 
  hex << x*(2*x-1)
 end
 
 solution = hex & pen & tri - [1]
 
#1533776805