#include <stdio.h>

/*
 * Project Euler 877 - XOR-Product Equation
 *
 * Over GF(2)[x], the equation (a*a) ^ (2*a*b) ^ (b*b) = 5
 * has solutions generated by the recurrence:
 *   a_{n+1} = b_n
 *   b_{n+1} = (b_n << 1) ^ a_n
 * seeded with (a_0, b_0) = (0, 3).
 *
 * X(N) = XOR of all b values where 0 <= a <= b <= N.
 */

typedef long long ll;
typedef unsigned long long ull;

int main(void) {
    ull limit = 1000000000000000000ULL; /* 10^18 */
    ull total = 0;
    ull a = 0, b = 3;

    while (b <= limit) {
        total ^= b;
        ull new_a = b;
        ull new_b = (b << 1) ^ a;
        a = new_a;
        b = new_b;
    }

    printf("%llu\n", total);
    return 0;
}
