# Pentagon numbers
# Problem 44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

require 'set'

LIMIT = 3000
pentagonals = (1..LIMIT).map { |n| n * (3 * n - 1) / 2 }
pen_set = pentagonals.to_set
min_D = nil

(1...LIMIT).each do |j|
  pj = pentagonals[j]
  (0...j).each do |k|
    pk = pentagonals[k]
    sum = pj + pk
    diff = (pj - pk).abs
    if pen_set.include?(sum) && pen_set.include?(diff)
      min_D = diff if min_D.nil? || diff < min_D
    end
  end
end

puts min_D

# set = []
# pen.each do |x|
      # pen.each do |y|
	  # set <<  (x - y) if  pen.include?(x+y) #and pen.include?(x-y) 
	# end
# end
 
# e = pen.to_enum