# Triangular, pentagonal, and hexagonal
# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

# Helper functions to check if a number is pentagonal or hexagonal
def is_pentagonal?(x)
  n = (Math.sqrt(24 * x + 1) + 1) / 6
  n == n.to_i
end

def is_hexagonal?(x)
  n = (Math.sqrt(8 * x + 1) + 1) / 4
  n == n.to_i
end

n = 286 # Start after T285 = 40755
loop do
  t = n * (n + 1) / 2
  if is_pentagonal?(t) && is_hexagonal?(t)
    puts t
    break
  end
  n += 1
end
