#!/usr/bin/env python3
"""
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def sum_even_fibonacci(limit: int) -> int:
    """Sum even Fibonacci numbers <= limit, starting sequence with 1, 2."""
    if limit < 2:
        return 0
    
    sum_even = 0
    prev_fib, curr_fib = 1, 2
    
    while curr_fib <= limit:
        if curr_fib % 2 == 0:
            sum_even += curr_fib
        prev_fib, curr_fib = curr_fib, prev_fib + curr_fib
    
    return sum_even


def main():
    result = sum_even_fibonacci(4_000_000)
    print(result)


if __name__ == "__main__":
    main()
