#!/usr/bin/env python3
"""
Project Euler Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

THRESHOLD = 500


def num_divisors(n: int) -> int:
    """Calculate number of divisors via prime factorization."""
    if n <= 1:
        return 1
    
    count = 1
    temp = n
    
    # Check for factor 2
    exp = 0
    while temp % 2 == 0:
        exp += 1
        temp //= 2
    if exp > 0:
        count *= (exp + 1)
    
    # Check for odd factors up to sqrt(n)
    i = 3
    while i * i <= temp:
        exp = 0
        while temp % i == 0:
            exp += 1
            temp //= i
        if exp > 0:
            count *= (exp + 1)
        i += 2
    
    # If temp is a prime number greater than 2
    if temp > 1:
        count *= 2
    
    return count


def triangular_numbers():
    """Generator for triangular numbers."""
    n = 1
    total = 0
    while True:
        total += n
        yield total
        n += 1


def main():
    for triangular in triangular_numbers():
        if num_divisors(triangular) > THRESHOLD:
            print(triangular)
            break


if __name__ == "__main__":
    main()
