#!/usr/bin/env python3
"""
Project Euler Problem 29: Distinct powers

How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
"""

from math import prod


def distinct_powers_count(min_a: int = 2, max_a: int = 100, min_b: int = 2, max_b: int = 100) -> int:
    """Compute the number of distinct a^b values for given ranges."""
    if min_a < 1 or max_a < min_a or min_b < 1 or max_b < min_b:
        raise ValueError("Invalid range")
    
    distinct_powers = set()
    
    for a in range(min_a, max_a + 1):
        power = a * a  # a^2
        distinct_powers.add(power)
        
        for b in range(min_b + 1, max_b + 1):
            power *= a
            distinct_powers.add(power)
    
    return len(distinct_powers)


def main():
    result = distinct_powers_count()
    print(result)


if __name__ == "__main__":
    main()
